/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pacientes.ui;

import com.pacientes.controller.IsExistsException;
import com.pacientes.controller.PacienteController;
import com.pacientes.util.Constant;
import com.pacientes.util.Util;
import javax.swing.JOptionPane;

/**
 *
 * @author Nestor_Velasquez
 */
public class Mantenimiento extends JAppletConFondo implements Constant{

    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    setImagen(RESOURCES_URL+"Background.jpg");
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edadPacientelb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        apellidoPacientelb = new javax.swing.JLabel();
        nombrePacientelb = new javax.swing.JLabel();
        nombrePacienteTf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        apellidoPacienteTf = new javax.swing.JTextField();
        mensajeErrorLb = new javax.swing.JLabel();
        edadPacienteFtf = new javax.swing.JFormattedTextField();

        jPanel1.setOpaque(false);

        edadPacientelb.setForeground(Constant.FONT_COLOR);
        edadPacientelb.setText("Edad");

        jLabel1.setFont(Constant.TITLE_FONT);
        jLabel1.setForeground(Constant.FONT_COLOR);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Paciente");

        apellidoPacientelb.setForeground(Constant.FONT_COLOR);
        apellidoPacientelb.setText("Apellido");

        nombrePacientelb.setForeground(Constant.FONT_COLOR);
        nombrePacientelb.setText("Nombre");

        jButton1.setText("Guardar");

        mensajeErrorLb.setForeground(new java.awt.Color(255, 0, 0));
        mensajeErrorLb.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(edadPacienteFtf)
                                        .addComponent(apellidoPacienteTf)
                                        .addComponent(nombrePacienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nombrePacientelb)
                                        .addComponent(edadPacientelb)
                                        .addComponent(apellidoPacientelb))))
                            .addComponent(mensajeErrorLb))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePacienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrePacientelb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoPacienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoPacientelb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadPacienteFtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadPacientelb))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeErrorLb))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre = nombrePacienteTf.getText(); 
        String apellido = apellidoPacienteTf.getText();
        String edad = edadPacienteFtf.getText();
        
        int option = 0;
        
        if(nombre.isEmpty()){
            mensajeErrorLb.setText("Favor ingresar un nombre");            
        }else if(apellido.isEmpty()){
            mensajeErrorLb.setText("Favor ingresar un apellido");
        }else if(edad.isEmpty()){
            mensajeErrorLb.setText("Favor ingresar la edad");
        }else if(!Util.numeroValido(edad)){
            mensajeErrorLb.setText("Favor ingresar una edad valida");
        }else {
            try {
                PacienteController.crearPaciente(nombre, apellido, edad);
                option = JOptionPane.showConfirmDialog(this, "Desea guardar otro?","Paciente Guardado",JOptionPane.YES_NO_OPTION);
                if(option==0){
                    cleanComponents();
                }else{
                    this.jPanel1.setVisible(false);
                }
                
            } catch (IsExistsException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(!mensajeErrorLb.getText().isEmpty()){
            mensajeErrorLb.setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void cleanComponents(){
        nombrePacienteTf.setText("");
        apellidoPacienteTf.setText("");
        edadPacienteFtf.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoPacienteTf;
    private javax.swing.JLabel apellidoPacientelb;
    private javax.swing.JFormattedTextField edadPacienteFtf;
    private javax.swing.JLabel edadPacientelb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensajeErrorLb;
    private javax.swing.JTextField nombrePacienteTf;
    private javax.swing.JLabel nombrePacientelb;
    // End of variables declaration//GEN-END:variables
}
