/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pacientes.ui;

import com.pacientes.controller.IsExistsException;
import com.pacientes.controller.PacienteController;
import com.pacientes.util.Constant;
import com.pacientes.util.Util;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Nestor_Velasquez
 */
public class Mantenimiento extends javax.swing.JApplet implements Constant{

    Image fondo;

    @Override
    public void paint(Graphics grphcs) {
        this.getGraphics().drawImage(Toolkit.getDefaultToolkit().getImage(RESOURCES_URL+"Background.jpg"),0,0,null);        
    }
    
    
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        
        this.getGraphics().drawImage(Toolkit.getDefaultToolkit().getImage(RESOURCES_URL+"Background.jpg"),0,0,null);
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();                    
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mensajeErrorLb = new javax.swing.JLabel();
        edadPacienteFtf = new javax.swing.JFormattedTextField();
        apellidoPacienteTf = new javax.swing.JTextField();
        nombrePacienteTf = new javax.swing.JTextField();
        nombrePacientelb = new javax.swing.JLabel();
        apellidoPacientelb = new javax.swing.JLabel();
        edadPacientelb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mensajeErrorLb.setForeground(new java.awt.Color(255, 0, 0));
        mensajeErrorLb.setText("jLabel2");

        nombrePacientelb.setText("Nombre");

        apellidoPacientelb.setText("Apellido");

        edadPacientelb.setText("Edad");

        jLabel1.setFont(Constant.TITLE_FONT);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(edadPacienteFtf)
                                .addComponent(apellidoPacienteTf)
                                .addComponent(nombrePacienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombrePacientelb)
                                .addComponent(edadPacientelb)
                                .addComponent(apellidoPacientelb))))
                    .addComponent(mensajeErrorLb)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePacienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrePacientelb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoPacienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoPacientelb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadPacienteFtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadPacientelb))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeErrorLb)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre = nombrePacienteTf.getText(); 
        String apellido = apellidoPacienteTf.getText();
        String edad = edadPacienteFtf.getText();
        
        if(nombre.isEmpty()){
            mensajeErrorLb.setText("Favor ingresar un nombre");            
        }else if(apellido.isEmpty()){
            mensajeErrorLb.setText("Favor ingresar un apellido");
        }else if(edad.isEmpty()){
            mensajeErrorLb.setText("Favor ingresar la edad");
        }else if(!Util.numeroValido(edad)){
            mensajeErrorLb.setText("Favor ingresar una edad valida");
        }else {
            try {
                PacienteController.crearPaciente(nombre, apellido, edad);
                mensajeErrorLb.setText("Paciente guardado");
            } catch (IsExistsException ex) {
                mensajeErrorLb.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoPacienteTf;
    private javax.swing.JLabel apellidoPacientelb;
    private javax.swing.JFormattedTextField edadPacienteFtf;
    private javax.swing.JLabel edadPacientelb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensajeErrorLb;
    private javax.swing.JTextField nombrePacienteTf;
    private javax.swing.JLabel nombrePacientelb;
    // End of variables declaration//GEN-END:variables
}
